manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: electronicmaterialsoffice
      url-base: https://github.com/electronicmaterialsoffice
  projects:
    - name: zmkfirmware
      remote: electronicmaterialsoffice
      revision: main
      import: app/west.yml
  self:
    path: config
